version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8000}:8000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-8000}
      - MONGO_URI=mongodb://mongo:27017/kanban
      - JWT_SECRET=${JWT_SECRET:-NOf9N92KWgiRSKR55GwSEW3vgGnrMRdJabHniDaHAswexR}
    depends_on:
      - mongo
    networks:
      - kanban-network
    command: npm run dev

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - kanban-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=kanban
    networks:
      - kanban-network

networks:
  kanban-network:
    driver: bridge
